[package]
name = "uuidv7"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "uuidv7"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies.rustler]
version = "0.29.0"

[dependencies.uuid]
version = "1.3.4"
features = ["v4"]
